name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      # --no-frozen-lockfile is required so that dependabot with automerge can work
      # https://github.com/dependabot/dependabot-core/issues/1736
      - run: pnpm install -r --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm test
        env:
          CI: true
